version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.23.1

workflows:
  version: 2

  test_orb:
    jobs:
      - orb-tools/test-in-builds:
          orb-location: src/orb.yaml
          orb-name: measureperf
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: spec/orb.yaml
